#!/bin/sh

# A sample post-deploy hook
#
# These environment variables are available:
# KAMAL_RECORDED_AT
# KAMAL_PERFORMER
# KAMAL_VERSION
# KAMAL_HOSTS
# KAMAL_ROLES (if set)
# KAMAL_DESTINATION (if set)
# KAMAL_RUNTIME

echo "$KAMAL_PERFORMER deployed $KAMAL_VERSION to $KAMAL_DESTINATION ($KAMAL_HOSTS) in $KAMAL_RUNTIME seconds"

#this should only run when it does not exist
#kamal accessory boot ollama
kamal accessory start ollama
kamal accessory exec ollama --reuse -v "ollama pull llama3:latest"
kamal accessory exec ollama --reuse -v "ollama list"

# make sure the data directory is writeable by our app
# Dynamically get the UID/GID of 'runner' inside the container
UID=$(kamal app exec --reuse "id -u runner")
GID=$(kamal app exec --reuse"id -g runner")

# Fix permissions on the host-mounted volume
kamal server exec honeypot "sudo chown -R $UID:$GID /opt/honeypot && sudo chmod -R 755 /opt/honeypot"
