#!/bin/sh
set -eux

# A sample post-deploy hook
#
# These environment variables are available:
# KAMAL_RECORDED_AT
# KAMAL_PERFORMER
# KAMAL_VERSION
# KAMAL_HOSTS
# KAMAL_ROLES (if set)
# KAMAL_DESTINATION (if set)
# KAMAL_RUNTIME

echo "$KAMAL_PERFORMER deployed $KAMAL_VERSION to $KAMAL_HOSTS in $KAMAL_RUNTIME seconds"

# Fix permissions on the host-mounted volume
kamal server exec "sudo chmod -R 777 /home/ubuntu/data"

#this should only run when it does not exist
#kamal accessory boot ollama
kamal accessory start ollama || true
kamal accessory exec ollama --reuse -v "ollama pull llama3:latest"
kamal accessory exec ollama --reuse -v "ollama list"
